### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by RaibowInvader** [peleon02/PUBG-Battlepoint-FarmBot#11]
C:\PUBG-Battlepoint-FarmBot-afkbot2.4\PUBG-Battlepoint-FarmBot-afkbot2.4>botgui.py
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\Python36-32\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Program Files (x86)\Python\Python36-32\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\PUBG-Battlepoint-FarmBot-afkbot2.4\PUBG-Battlepoint-FarmBot-afkbot2.4\FarmBot.py", line 231, in run
    tolerance=color_tolerance
  File "C:\PUBG-Battlepoint-FarmBot-afkbot2.4\PUBG-Battlepoint-FarmBot-afkbot2.4\FarmBot.py", line 67, in pixelMatchesColor
    exR, exG, exB = int(expectedRGBColor[0]),
ValueError: not enough values to unpack (expected 3, got 1)

**Comment by COMMANDERWONG** [comment]
Same.

**Comment by peleon02** [comment]
Fixed

**Comment by RaibowInvader** [comment]
Thanks
